In [2]:
#Shambhavii V. Jaiswal
#PRN : 23070521133
import nbformat as nbf

nb = nbf.v4.new_notebook()

cells = []

# Title
cells.append(nbf.v4.new_markdown_cell("""
# Practical 1
# Introduction to Deep Learning Frameworks

## Aim
To explore the TensorFlow/Keras environment, create a basic neural network architecture, and understand tensors, layers, activation functions, and optimizers.

---

## Problem Statement
Explore the TensorFlow/Keras environment, create a simple neural network architecture, and understand tensors, layers, activation functions, and optimizers.

## Objectives
- Install and import TensorFlow/Keras.
- Understand tensors.
- Create a simple neural network.
- Explore activation functions.
- Compile a model using an optimizer and loss function.
"""))

# Import TensorFlow
cells.append(nbf.v4.new_code_cell("""
import tensorflow as tf

print("TensorFlow Version:", tf.__version__)
"""))

# Tensor explanation
cells.append(nbf.v4.new_markdown_cell("""
## Understanding Tensors

A tensor is the fundamental data structure in TensorFlow.
It is similar to a NumPy array but is optimized for efficient computation on CPUs, GPUs, and TPUs.
"""))

# Tensor creation
cells.append(nbf.v4.new_code_cell("""
scalar = tf.constant(10)

vector = tf.constant([1,2,3,4])

matrix = tf.constant([[1,2],
                      [3,4]])

print("Scalar:")
print(scalar)

print("\nVector:")
print(vector)

print("\nMatrix:")
print(matrix)
"""))

# Neural network explanation
cells.append(nbf.v4.new_markdown_cell("""
## Creating a Simple Neural Network

TensorFlow provides the Keras API to build deep learning models easily.
The Sequential API allows layers to be stacked one after another.
"""))

# Model creation
cells.append(nbf.v4.new_code_cell("""
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential([
    layers.Input(shape=(4,)),
    layers.Dense(16, activation='relu'),
    layers.Dense(8, activation='relu'),
    layers.Dense(3, activation='softmax')
])

model.summary()
"""))

# Activation functions
cells.append(nbf.v4.new_markdown_cell("""
## Activation Functions

Common activation functions used in deep learning include:

- ReLU
- Sigmoid
- Tanh
- Softmax

These functions introduce non-linearity into the neural network.
"""))

cells.append(nbf.v4.new_code_cell("""
print("Hidden Layer Activation : ReLU")
print("Output Layer Activation : Softmax")
"""))

# Model compilation
cells.append(nbf.v4.new_markdown_cell("""
## Model Compilation

Before training, a neural network must be compiled by specifying:

- Optimizer
- Loss Function
- Evaluation Metric
"""))

cells.append(nbf.v4.new_code_cell("""
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

print("Model compiled successfully.")
"""))

# Training explanation
cells.append(nbf.v4.new_markdown_cell("""
## Model Training

A model is generally trained using the `fit()` function.

Example:

```python
model.fit(X_train, y_train,
          epochs=10,
          batch_size=32)
```
"""))

## Generating Dummy Training Data

To demonstrate the model's `fit()` method, we need to create some dummy training data that matches the input and output shapes of our defined model.

In [4]:
import numpy as np
import tensorflow as tf

# Define the number of samples for dummy data
num_samples = 100

# Generate dummy input features (X_train) with 4 features
X_train = np.random.rand(num_samples, 4).astype(np.float32);

# Generate dummy target labels (y_train) for 3 classes (0, 1, or 2)
# Then, one-hot encode these labels
y_train_labels = np.random.randint(0, 3, num_samples)
y_train = tf.keras.utils.to_categorical(y_train_labels, num_classes=3)

print("Shape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)

print("\nFirst 5 rows of X_train:\n", X_train[:5])
print("\nFirst 5 rows of y_train (one-hot encoded):\n", y_train[:5])

Shape of X_train: (100, 4)
Shape of y_train: (100, 3)

First 5 rows of X_train:
 [[0.8245677  0.5551385  0.01870054 0.2833949 ]
 [0.66360956 0.09463435 0.52764416 0.3587182 ]
 [0.33788082 0.56233466 0.24008217 0.13678361]
 [0.18132451 0.39191276 0.80929184 0.4664163 ]
 [0.5703815  0.56778604 0.02646145 0.2474806 ]]

First 5 rows of y_train (one-hot encoded):
 [[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


## Model Training with Dummy Data

Now, let's train the model using the generated `X_train` and `y_train`.

In [6]:
from tensorflow import keras
from tensorflow.keras import layers
import tensorflow as tf # Ensure tf is imported for keras utilities, though not strictly needed for model building here.

# Model definition (copied from the intended model creation cell)
model = keras.Sequential([
    layers.Input(shape=(4,)),
    layers.Dense(16, activation='relu'),
    layers.Dense(8, activation='relu'),
    layers.Dense(3, activation='softmax')
])

# Model compilation (copied from the intended model compilation cell)
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(X_train, y_train,
                    epochs=10,
                    batch_size=32,
                    verbose=1)

print("\nModel training complete.")

Epoch 1/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.3700 - loss: 1.0948
Epoch 2/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4000 - loss: 1.0942 
Epoch 3/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4200 - loss: 1.0937
Epoch 4/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4200 - loss: 1.0933
Epoch 5/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.3900 - loss: 1.0928
Epoch 6/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4000 - loss: 1.0926
Epoch 7/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3900 - loss: 1.0921
Epoch 8/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.3800 - loss: 1.0919
Epoch 9/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3900 - loss: 1.0915
Epoch 10/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4200 - loss: 1.0910

Model training complete.
